USE [master]
GO

/****** Object:  Database [user-blockchain]    Script Date: 6/1/2023 3:14:58 PM ******/
CREATE DATABASE [user-blockchain]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'user-blockchain', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\user-blockchain.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'user-blockchain_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\user-blockchain_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [user-blockchain].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [user-blockchain] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [user-blockchain] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [user-blockchain] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [user-blockchain] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [user-blockchain] SET ARITHABORT OFF 
GO

ALTER DATABASE [user-blockchain] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [user-blockchain] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [user-blockchain] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [user-blockchain] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [user-blockchain] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [user-blockchain] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [user-blockchain] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [user-blockchain] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [user-blockchain] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [user-blockchain] SET  DISABLE_BROKER 
GO

ALTER DATABASE [user-blockchain] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [user-blockchain] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [user-blockchain] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [user-blockchain] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [user-blockchain] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [user-blockchain] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [user-blockchain] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [user-blockchain] SET RECOVERY FULL 
GO

ALTER DATABASE [user-blockchain] SET  MULTI_USER 
GO

ALTER DATABASE [user-blockchain] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [user-blockchain] SET DB_CHAINING OFF 
GO

ALTER DATABASE [user-blockchain] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [user-blockchain] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [user-blockchain] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [user-blockchain] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [user-blockchain] SET QUERY_STORE = OFF
GO

ALTER DATABASE [user-blockchain] SET  READ_WRITE 
GO
---------------------------------------------------------------

USE [user-blockchain]
GO


/****** Object:  Table [dbo].[blockchain]    Script Date: 6/1/2023 3:17:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[blockchain](
	[block_id] [int] IDENTITY(1,1) NOT NULL,
	[timestamp] [datetime] NOT NULL,
	[previous_hash] [varchar](256) NOT NULL,
	[hash] [varchar](256) NOT NULL,
	[proof] [int] NOT NULL,
	[user_id] [int] NOT NULL,
	[name] [varchar](100) NOT NULL,
	[num_coins] [int] NOT NULL,
	[content] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[block_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[blockchain]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[user] ([id])
GO

/****** Object:  Table [dbo].[user]    Script Date: 6/1/2023 3:17:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[user](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[password] [varchar](1000) NOT NULL,
	[public_key] [varchar](max) NOT NULL,
	[private_key] [varchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
